import { Restaurant, Listing, Order, Notification } from '@/shared/types';

export const mockRestaurants: Restaurant[] = [
  {
    id: 'rest-1',
    userId: 'user-rest-1',
    name: 'Green Leaf Bistro',
    description: 'Farm-to-table restaurant with fresh organic ingredients',
    address: '123 Eco Street, Downtown',
    phone: '+1 555-0101',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&h=200&fit=crop',
    rating: 4.8,
    totalOrders: 342,
    category: 'Bistro',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'rest-2',
    userId: 'user-rest-2',
    name: 'Sunrise Bakery',
    description: 'Artisan bakery with fresh daily bakes',
    address: '456 Baker Avenue',
    phone: '+1 555-0102',
    logo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&h=200&fit=crop',
    rating: 4.9,
    totalOrders: 567,
    category: 'Bakery',
    createdAt: new Date('2023-11-20').toISOString(),
  },
  {
    id: 'rest-3',
    userId: 'user-rest-3',
    name: 'Ocean Pearl Sushi',
    description: 'Fresh sushi and Japanese cuisine',
    address: '789 Harbor Road',
    phone: '+1 555-0103',
    logo: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=200&h=200&fit=crop',
    rating: 4.7,
    totalOrders: 289,
    category: 'Sushi',
    createdAt: new Date('2024-02-10').toISOString(),
  },
];

const now = new Date();
const oneHourLater = new Date(now.getTime() + 60 * 60 * 1000);
const twoHoursLater = new Date(now.getTime() + 2 * 60 * 60 * 1000);
const threeHoursLater = new Date(now.getTime() + 3 * 60 * 60 * 1000);
const fourHoursLater = new Date(now.getTime() + 4 * 60 * 60 * 1000);
const fiveHoursLater = new Date(now.getTime() + 5 * 60 * 60 * 1000);
const sixHoursLater = new Date(now.getTime() + 6 * 60 * 60 * 1000);

export const mockListings: Listing[] = [
  {
    id: 'list-1',
    restaurantId: 'rest-1',
    title: 'Fresh Garden Salad Bowl',
    description: 'Healthy mixed greens with house vinaigrette, must go today!',
    originalPrice: 12.99,
    discountedPrice: 5.99,
    quantity: 8,
    remainingQuantity: 3,
    expiresAt: oneHourLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
    tags: ['Salad', 'Healthy', 'Vegan'],
    isPriorityAccess: false,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'list-2',
    restaurantId: 'rest-2',
    title: 'Assorted Pastry Box',
    description: '6 fresh pastries - croissants, danishes, and muffins from this morning',
    originalPrice: 18.99,
    discountedPrice: 7.99,
    quantity: 5,
    remainingQuantity: 2,
    expiresAt: twoHoursLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop',
    tags: ['Bakery', 'Breakfast', 'Pastries'],
    isPriorityAccess: true,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'list-3',
    restaurantId: 'rest-3',
    title: 'Sushi Combo Platter',
    description: '12 pieces of fresh sushi - California rolls and nigiri selection',
    originalPrice: 24.99,
    discountedPrice: 12.99,
    quantity: 10,
    remainingQuantity: 7,
    expiresAt: threeHoursLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&h=400&fit=crop',
    tags: ['Sushi', 'Japanese', 'Seafood'],
    isPriorityAccess: false,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'list-4',
    restaurantId: 'rest-1',
    title: 'Grilled Veggie Sandwich',
    description: 'Whole wheat with roasted vegetables and pesto mayo',
    originalPrice: 9.99,
    discountedPrice: 4.99,
    quantity: 6,
    remainingQuantity: 4,
    expiresAt: fourHoursLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&h=400&fit=crop',
    tags: ['Sandwich', 'Vegetarian', 'Lunch'],
    isPriorityAccess: false,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'list-5',
    restaurantId: 'rest-2',
    title: 'Artisan Sourdough Loaf',
    description: 'Fresh baked sourdough from this morning - perfect for toast',
    originalPrice: 8.99,
    discountedPrice: 3.99,
    quantity: 12,
    remainingQuantity: 8,
    expiresAt: fiveHoursLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=600&h=400&fit=crop',
    tags: ['Bread', 'Bakery', 'Breakfast'],
    isPriorityAccess: true,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'list-6',
    restaurantId: 'rest-3',
    title: 'Ramen Bowl Special',
    description: 'Rich tonkotsu ramen with pork belly and soft-boiled egg',
    originalPrice: 15.99,
    discountedPrice: 8.99,
    quantity: 8,
    remainingQuantity: 6,
    expiresAt: sixHoursLater.toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    tags: ['Ramen', 'Japanese', 'Dinner'],
    isPriorityAccess: false,
    createdAt: new Date().toISOString(),
    status: 'active',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    userId: 'user-1',
    items: [
      {
        listing: mockListings[0],
        quantity: 1,
        priceAtPurchase: 5.99,
      },
    ],
    subtotal: 5.99,
    serviceFee: 0,
    savings: 7.00,
    totalPrice: 5.99,
    status: 'confirmed',
    pickupTime: new Date(now.getTime() + 30 * 60 * 1000).toISOString(),
    restaurantIds: ['rest-1'],
    createdAt: new Date(now.getTime() - 10 * 60 * 1000).toISOString(),
    listingId: 'list-1',
    quantity: 1,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: '🔥 New Hot Deal!',
    message: 'Sunrise Bakery just added Assorted Pastry Box at 58% off!',
    type: 'new_listing',
    isRead: false,
    createdAt: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: '⏰ Expiring Soon!',
    message: 'Fresh Garden Salad Bowl expires in 1 hour',
    type: 'expiring_soon',
    isRead: false,
    createdAt: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    title: '✅ Order Confirmed',
    message: 'Your order from Green Leaf Bistro is ready for pickup',
    type: 'order_update',
    isRead: true,
    createdAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
  },
];
